INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('John', 'Smith', 'js@gmail.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Julie', 'Black', 'jb@gmail.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Reza', 'Bayat', 'rb@gamil.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Omid', 'Ali', 'oa@gmail.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Mark', 'Ram', 'mr@gmail.com');
INSERT INTO USER (FIRST_NAME, LAST_NAME, EMAIL_ADDRESS) VALUES ('Asad', 'Bayat', 'ab@gmail.com');


INSERT INTO IP_ADDRESS(IP_ADDRESS, CURRENT_STATUS, CIDR_BLOCK, CREATED_BY_USER, UPDATED_BY_USER) VALUES ('132.125.0.1','AVAILABLE','10.0.0.0/24', (SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='oa@gmail.com'), (SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='oa@gmail.com'));
INSERT INTO IP_ADDRESS(IP_ADDRESS, CURRENT_STATUS, CIDR_BLOCK, CREATED_BY_USER, UPDATED_BY_USER) VALUES ('132.125.0.2','AVAILABLE','10.0.0.1/12',(SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='oa@gmail.com'), (SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='ab@gmail.com'));
INSERT INTO IP_ADDRESS(IP_ADDRESS, CURRENT_STATUS, CIDR_BLOCK, CREATED_BY_USER, UPDATED_BY_USER) VALUES ('132.125.0.3','ACQUIRED','10.0.0.2/6', (SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='mr@gmail.com'), (SELECT USER_ID FROM USER WHERE EMAIL_ADDRESS='mr@gmail.com'));